- name: Prepare containers
  hosts: localhost
  connection: local
  tasks:
    - name: Check if 'registry' container is running
      shell: "{% raw %}docker ps --filter 'name=registry' --filter 'status=running' --format '{{.Names}}'{% endraw %}"
      register: registry_is_running
      changed_when: false

    - name: Bring up datanode registry
      ansible.builtin.shell: >
        docker run -d --restart always --name datanode_registry
        -v /mnt/docker_registry:/var/lib/registry
        -p 8009:5000
        iguazio/registry:latest
      args:
        executable: /bin/bash
      environment:
        REGISTRY_STORAGE_FILESYSTEM_MAXTHREADS: "{{ ansible_local['registry']['kompton']['registry_fs_maxthreads'] }}"
      when: registry_is_running.stdout == ""

    - name: Set outputs dir
      set_fact:
        outputs_dir: "{{ (playbook_dir + '/../') | realpath }}"
        kompton_dir: "{{ (playbook_dir + '/../../../deploy') | realpath }}"

    - name: Start nginx for Kubespray
      ansible.builtin.shell: |
        set -o pipefail
        docker rm -f kubespray_nginx || true
        docker run \
        -d -p 18080:80 \
        --restart always \
        --name kubespray_nginx \
        -v "{{ outputs_dir }}:/usr/share/nginx/html" \
        iguazio/nginx_server:latest

    - name: Force skopeo bin
      unarchive:
        src: "{{ outputs_dir }}/files/skopeo-1.14.0.tar.gz"
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0o755
      become: true

    - name: Find all tar.gz files in the directory
      find:
        paths:
          - "{{ outputs_dir }}/images"
        patterns:
          - "*.tar.gz"
          - "*.tar"
      register: tarballs

    - name: Push k8s images to datanode registry
      shell: |
        python3 /usr/local/bin/igz_push.py \
        -sl "{{ tarballs.files | map(attribute='path') | list }}" \
        -hf "{{ kompton_dir }}/inventory/group_vars/all/020_packaging.yml" \
        -dr localhost:8009
      args:
        executable: /bin/bash
      become: true
