- name: Prepare containers
  hosts: k8s_clients
  tasks:
    - name: Check if datanode registry is running
      ansible.builtin.shell: docker ps --quiet --filter name=kompton_registry
      register: registry_is_running
      changed_when: false
      tags:
        - skip_ansible_lint

    - name: Bring up Kompton registry
      ansible.builtin.shell: >
        docker run -d --restart always --name kompton_registry
        -v {{ ansible_local['registry']['kompton']['docker_registry_path'] }}:/var/lib/registry
        -p {{ ansible_local['registry']['kompton']['kompton_registry_port'] }}:5000
        {{ ansible_local['registry']['kompton']['docker_registry_image'] }}
      args:
        executable: /bin/bash
      environment:
        REGISTRY_STORAGE_FILESYSTEM_MAXTHREADS: "{{ ansible_local['registry']['kompton']['registry_fs_maxthreads'] }}"
      when: registry_is_running.stdout == ""
      tags:
        - skip_ansible_lint

    - name: Start nginx for Kubespray
      ansible.builtin.shell: |
        set -o pipefail
        docker rm -f kubespray_nginx || true
        docker run \
        -d -p 18080:80 \
        --restart always \
        --name kubespray_nginx \
        -v "{{ ansible_local['registry']['kompton']['kubespray_dir'] }}/outputs:/usr/share/nginx/html" \
        iguazio/nginx_server:latest
      tags:
        - skip_ansible_lint

    - name: Start HAProxy service on data nodes
      ansible.builtin.systemd:
        name: haproxy
        state: started
      become: true
      when:
        - ansible_local.haproxy.haproxy.enabled is defined
        - ansible_local.haproxy.haproxy.enabled == "true"
